var agenda = [];
agenda[0] = "Jose Vicente";
agenda[1] = "Juan";
agenda[2] = "Jorge";
agenda[3] = "Jacinto";
console.table(agenda);
agenda.push("Julia");
console.table(agenda);
agenda.pop();
console.log(agenda);
agenda.splice(0,1);
console.table(agenda);